image: docker:latest
services:
  - docker:dind

stages:
  - build
  - deploy

build:
  image: gradle:5.0-jdk8-alpine
  stage: build
  script:
    - whoami
    - gradle build --info
  artifacts:
    paths:
      - build/libs/*.jar

deploy_staging:
  stage: deploy
  script:
    - ls
    - pwd
    - docker build -t ccrest config.dockerfile
    - docker container stop ccrest || true
    - docker run --net=host --name ccrest -d ccrest
  only:
    - master