image: docker:latest
services:
  - docker:dind

stages:
  - build
  - package
  - deploy

build:
  image: gradle:5.0-jdk8-alpine
  stage: build
  script:
    - gradle build
  artifacts:
    paths:
      - build/libs/*.jar

package:
  stage: package
  script:
    - docker build -t registry.gitlab.com/mathflake/api .
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker push registry.gitlab.com/mathflake/api

deploy_staging:
  stage: deploy
  script:
    - apk upgrade && apk update
    - apk add openssh-client
    - apk add sshpass
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker pull registry.gitlab.com/mathflake/api
    - docker container stop mathflake_api && docker container rm mathflake_api || true
    - docker run --net=host --name mathflake_api -p 80:80 -d registry.gitlab.com/mathflake/api
  environment:
    name: staging
    url: https://mathflake.com
  only:
    - master