image: docker:latest
services:
  - docker:dind

stages:
  - build
  - deploy

build:
  image: gradle:5.0-jdk8-alpine
  stage: build
  script:
    - whoami
    - gradle build --info
    - whoami
    - pwd
    - cp build/libs/*jar /host
  artifacts:
    paths:
      - build/libs/*.jar

deploy_staging:
  stage: deploy
  script:
    - apk upgrade && apk update
    - apk add openssh-client
    - apk add sshpass
    - ls
    - pwd
    - whoami
    - ifconfig
    - sshpass -p "$STAGING_SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no $STAGING_SERVER_USER@$STAGING_SERVER pwd
  only:
    - master