image: docker:latest
services:
  - docker:dind

stages:
  - build
  - deploy

build:
  image: gradle:5.0-jdk8-alpine
  stage: build
  script:
    - whoami
    - gradle build --info
  artifacts:
    paths:
      - build/libs/*.jar

deploy_staging:
  stage: deploy
  script:
    - docker build -t ccrest
    - docker container stop ccrest || true
    - docker run --net=host --name ccrest -d ccrest
  environment:
    name: staging
    url: https://mathflake.com
  only:
    - master